package frc.controls;

public enum ButtonCode {
	A,
	B,
	X,
	Y,
	LEFTBUMPER,
	RIGHTBUMPER,
	BACK,
	START,
	LEFTSTICK,
	RIGHTSTICK,
	SHOOTER_PROFILE_MANUAL_OVERRIDE,
	SHOOTER_REV,
	SHOOTER_OVERRIDE,
	SHOOTER_LAUNCH_PAD_SHOT,
	SHOOTER_TARMAC_SHOT,
	SHOOTER_LOW_GOAL_SHOT,
	SHOOTER_AUTO_RADIUS_SHOT,
	FEEDER_WHEEL_REVERSE,
	CLIMBER_EXTEND,
	CLIMBER_RETRACT,
	CLIMBER_OVERRIDE,
	CLIMBER_EXTEND_SLOWLY,
	CLIMBER_RETRACT_SLOWLY
}
