package frc.controls;

public enum ButtonCode {
	A,
	B,
	X,
	Y,
	LEFTBUMPER,
	RIGHTBUMPER,
	BACK,
	START,
	LEFTSTICK,
	RIGHTSTICK,
	LIMELIGHT_LIGHT_OFF_OVERRIDE,
	SHOOTER_REV,
	SHOOTER_OVERRIDE,
	SHOOTER_LAUNCH_PAD_SHOT,
	SHOOTER_TARMAC_SHOT,
	SHOOTER_LOW_GOAL_SHOT,
	SHOOTER_AUTO_RADIUS_SHOT,
	FEEDER_WHEEL_REVERSE,
	CLIMBER_EXTEND,
	CLIMBER_RETRACT,
	CLIMBER_OVERRIDE,
	TURRET_HOME,
	TURRET_DISABLED_OVERRIDE,
	TOGGLE_COLOR_SENSING_FEATURES
}
