package frc.controls;

public enum ButtonCode {
	A(1),
	B(2),
	X(3),
	Y(4),
	LEFTBUMPER(5),
	RIGHTBUMPER(6),
	BACK(7),
	START(8),
	LEFTSTICK(9),
	RIGHTSTICK(10),

	// OPAD 1
	LIMELIGHT_LIGHT_OFF_OVERRIDE(1),
	SHOOTER_REV(2),
	CLIMBER_OVERRIDE(3),
	TURRET_DISABLED_OVERRIDE(4),
	SHOOTER_LAUNCH_PAD_SHOT(9),
	SHOOTER_TARMAC_SHOT(10),
	SHOOTER_LOW_GOAL_SHOT(11),
	SHOOTER_AUTO_RADIUS_SHOT(12),

	// OPAD 2
	CLIMBER_EXTEND(1),
	CLIMBER_RETRACT(2),
	TURRET_HOME(3),
	TOGGLE_COLOR_SENSING_FEATURES(4),
	FEEDER_WHEEL_REVERSE(6);

	public final int value;
	
	ButtonCode(int initValue)
	{
		this.value = initValue;
	}
}